spring:
  application:
    name: configcenter
  profiles:
    active: native
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
    config:
      server:
        git:
          uri: https://github.com/DeathKnightH/config-repo
#          search-paths: master
#        本地文件系统作为配置仓库
#        native:
#          search-locations: file:///D:/configRepo
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8000/eureka/